### ISSUE TITLE
This code is giving client id not found error

### ISSUE THREAD

**Issue by Arvind644** [hashicorp/learn-terraform-provision-aks-cluster#14]
While running terraform apply, it is giving me this error

```
│ Error: creating Managed Kubernetes Cluster "novel-whale-aks" (Resource Group "novel-whale-rg"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ServicePrincipalNotFound" Message="Service principal clientID: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa not found in Active Directory tenant 

with azurerm_kubernetes_cluster.default,
│   on aks-cluster.tf line 16, in resource "azurerm_kubernetes_cluster" "default":
│   16: resource "azurerm_kubernetes_cluster" "default" {
```

**Comment by BrianMMcClain** [comment]
Hi @Arvind644! Sorry for the delay getting back to you on this issue. This looks like you may be using the default values in the `terraform.tfvars` file. Can you confirm that you have added the `appId` and `password` shown in the output of the `az ad sp create-for-rbac --skip-assignment` command to your `terraform.tfvars` file? 

Another think to check is to ensure that your `az` CLI is properly authenticated. If you have multiple accounts, you may need to configure which account the `az` CLI is pointing to with the `az account set` command. Refer to the [Logging into the Azure CLI](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli#logging-into-the-azure-cli) docs for more information.

If you're still seeing the issue, please let me know and I'll he happy to diagnose further. Thanks!

**Comment by BrianMMcClain** [comment]
Marking this as closed for now, but if you're still seeing this issue, please feel free to reopen and I'll he happy to help 😄
