### ISSUE TITLE
VM size not supported 

### ISSUE THREAD

**Issue by infraGoga** [hashicorp/learn-terraform-provision-aks-cluster#15]
While applying the plan i received this error :"The VM size of Standard_B2s is not allowed in your subscription in location 'westus2'

exactly:
Error: creating Managed Kubernetes Cluster "caring-pelican-aks" (Resource Group "caring-pelican-rg"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="The VM size of Standard_B2s is not allowed in your subscription in location 'westus2'. The available VM sizes are 'standard_d16pds_v5,standard_d16plds_v5,standard_d16pls_v5,standard_d16ps_v5,standard_d2pds_v5,standard_d2plds_v5,standard_d2pls_v5,standard_d2ps_v5,standard_d32pds_v5,standard_d32plds_v5,standard_d32pls_v5,standard_d32ps_v5,standard_d48pds_v5,standard_d48plds_v5,standard_d48pls_v5,standard_d48ps_v5,standard_d4pds_v5,standard_d4plds_v5,standard_d4pls_v5,standard_d4ps_v5,standard_d64pds_v5,standard_d64plds_v5,standard_d64pls_v5,standard_d64ps_v5,standard_d8pds_v5,standard_d8plds_v5,standard_d8pls_v5,standard_d8ps_v5,standard_dc16ds_v3,standard_dc16s_v3,standard_dc24ds_v3,standard_dc24s_v3,standard_dc2ds_v3,standard_dc2s_v3,standard_dc32ds_v3,standard_dc32s_v3,standard_dc48ds_v3,standard_dc48s_v3,standard_dc4ds_v3,standard_dc4s_v3,standard_dc8ds_v3,standard_dc8s_v3,standard_e16pds_v5,standard_e16ps_v5,standard_e20pds_v5,standard_e20ps_v5,standard_e2pds_v5,standard_e2ps_v5,standard_e32pds_v5,standard_e32ps_v5,standard_e4pds_v5,standard_e4ps_v5,standard_e8pds_v5,standard_e8ps_v5,standard_fx12mds,standard_fx24mds,standard_fx36mds,standard_fx48mds,standard_fx4mds,standard_hb120-16rs_v2,standard_hb120-32rs_v2,standard_hb120-64rs_v2,standard_hb120-96rs_v2,standard_hb120rs_v2,standard_hc44-16rs,standard_hc44-32rs,standard_hc44rs' For more details, please visit https://aka.ms/aks/quotas-skus-regions"

**Comment by BrianMMcClain** [comment]
Hi @infraGoga! We recently updated this repo  to use a different instance size that should be supported in most subscriptions in westus2 right now. We've also added a clarifying callout to the tutorial should this issue arise again in the future that points to the relevant Azure documentation. Thanks for pointing this out! Closing this for now but if you're still seeing this issue, please let us know and we'll be happy to take another look!
