### ISSUE TITLE
README - need to add additional step prior to launching k8 dashboard

### ISSUE THREAD

**Issue by bugbiteme** [hashicorp/learn-terraform-provision-aks-cluster#4]
before you can launch the k8 dashboard, you need to enable the kube-dashboard in azure:

az aks enable-addons --addons kube-dashboard --resource-group $(terraform output resource_group_name) --name $(terraform output kubernetes_cluster_name)

**Comment by im2nguyen** [comment]
Good catch, going to update [`aks_cluster.tf`](https://github.com/hashicorp/learn-terraform-provision-aks-cluster/blob/master/aks-cluster.tf) with [`kube_dashboard`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kube_dashboard) instead.

This way, all k8s cluster management is handled by Terraform and you don't have to run any additional commands :)
