### ISSUE TITLE
K8S Dashboard Add-on deprecated

### ISSUE THREAD

**Issue by amreshkris** [hashicorp/learn-terraform-provision-aks-cluster#7]
Repo needs an update as the add-on dashboard used in the example is no longer supported with K8S V >=1.19.0.

https://kubernetes.io/docs/concepts/cluster-administration/addons/

**Comment by im2nguyen** [comment]
Thanks for reporting @amreshkris, will address this soon. Will most likely remove the `addon_profile.kube_dashboard` attribute and have users add the kubernetes dashboard manually, like the [EKS tutorial](https://learn.hashicorp.com/tutorials/terraform/eks)

Additional resources for reference:
- https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard
- https://docs.microsoft.com/en-us/azure/aks/kubernetes-portal
